server:
  port: 8081
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/expensemanager?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: pass@word1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        generate_statistics: true  
    show-sql: true
    generate-ddl: true
  jackson:
    serialization:
      write-date-keys-as-timestamps: false
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

